[tasks.web]
command = "trunk"
args = ["serve", "--release"]

[tasks.dev]
command = "cargo"
args = ["run", "--features", "\"dev, dynamic_linking\""]

[tasks.dyn]
command = "cargo"
args = ["run", "--features", "dynamic_linking"]


[tasks.release]
command = "cargo"
args = ["build", "--profile", "release-dist"]
