[tasks.web]
command = "trunk"
args = ["serve", "--release", "--features", "web"]


[tasks.run]
command = "cargo"
args = ["run", "--features", "native"]

[tasks.dev]
command = "cargo"
args = ["run", "--features", "dev dynamic_linking native"]

[tasks.dyn]
command = "cargo"
args = ["run", "--features", "dynamic_linking native"]


[tasks.release]
command = "cargo"
args = ["build", "--features", "native", "--profile", "release-dist"]
